package Modelo;
// Generated 06/06/2020 08:19:41 PM by Hibernate Tools 3.6.0



/**
 * Promocion generated by hbm2java
 */
public class Promocion  implements java.io.Serializable {


     private Integer idPromocion;
     private String promocion;

    public Promocion() {
    }

    public Promocion(String promocion) {
       this.promocion = promocion;
    }
   
    public Integer getIdPromocion() {
        return this.idPromocion;
    }
    
    public void setIdPromocion(Integer idPromocion) {
        this.idPromocion = idPromocion;
    }
    public String getPromocion() {
        return this.promocion;
    }
    
    public void setPromocion(String promocion) {
        this.promocion = promocion;
    }




}


